name: "Generate Repo File List"
description: "Generates an HTML file list for a GitHub repository with links to each file."
inputs:
  repo-url:
    description: "GitHub repository URL to use for generating file links. Default is determined by the Git configuration."
    required: false
  fallback-repo-url:
    description: "Fallback GitHub repository URL to use if the default URL cannot be determined."
    required: false
    default: "https://github.com/author/repo"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--log-level"
    - ${{ inputs.log-level }}
    - "--directory"
    - ${{ inputs.directory }}
    - "--repo-url"
    - ${{ inputs.repo-url }}
    - "--fallback-repo-url"
    - ${{ inputs.fallback-repo-url }}
    - "--output-format"
    - ${{ inputs.output-format }}
    - "--output-file"
    - ${{ inputs.output-file }}
    - "--color-source"
    - ${{ inputs.color-source }}
    - "--color-list"
    - ${{ inputs.color-list }}
    - "--color-range"
    - ${{ inputs.color-range }}
    - "--exclude-dark-colors"
    - ${{ inputs.exclude-dark-colors }}
    - "--exclude-bright-colors"
    - ${{ inputs.exclude-bright-colors }}
    - "--exclude-blacks"
    - ${{ inputs.exclude-blacks }}
    - "--max-attempts"
    - ${{ inputs.max-attempts }}
    - "--exclude-blacks-threshold"
    - ${{ inputs.exclude-blacks-threshold }}
    - "--ensure-readable-colors"
    - ${{ inputs.ensure-readable-colors }}
    - "--repo-root-header"
    - ${{ inputs.repo-root-header }}
    - "--header-text"
    - ${{ inputs.header-text }}
    - "--intro-text"
    - ${{ inputs.intro-text }}
    - "--dark-color-luminance-threshold"
    - ${{ inputs.dark-color-luminance-threshold }}
    - "--bright-color-luminance-threshold"
    - ${{ inputs.bright-color-luminance-threshold }}
    - "--chunk-size"
    - ${{ inputs.chunk-size }}
    - "--viewport-mobile"
    - ${{ inputs.viewport-mobile }}
    - "--viewport-tablet"
    - ${{ inputs.viewport-tablet }}
    - "--viewport-small-desktop"
    - ${{ inputs.viewport-small-desktop }}
    - "--root-margin-large-desktop"
    - ${{ inputs.root-margin-large-desktop }}
    - "--root-margin-small-desktop"
    - ${{ inputs.root-margin-small-desktop }}
    - "--root-margin-tablet"
    - ${{ inputs.root-margin-tablet }}
    - "--root-margin-mobile"
    - ${{ inputs.root-margin-mobile }}
